spring.application.name=location-service
server.port=8082

#Redis Configuration
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

#Actuator
management.endpoints.web.exposure.include=health,info
